#!/usr/bin/env bash

gnome-terminal -- roslaunch drone_sim multi_drone.launch &

sleep 10
gnome-terminal -- ~/catkin_ws/src/drone_sim/scripts/drone1.sh &
gnome-terminal -- ~/catkin_ws/src/drone_sim/scripts/drone2.sh &

sleep 25
gnome-terminal -- python3 ~/catkin_ws/src/drone_sim/src/target_controller.py & 
gnome-terminal -- python3 ~/catkin_ws/src/drone_sim/src/visual_servo.py &

sleep 1
gnome-terminal -- python3 ~/catkin_ws/src/drone_sim/src/detect.py &
